---
run:
  deadline: 5m
  skip-files:
    - ".*\\.pb\\.go$"

linters-settings:
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 20
  maligned:
    suggest-new: true
  nakedret:
    max-func-lines: 0

linters:
  enable-all: true
  disable:
    - errcheck
    - lll
