language: minimal

sudo: required

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
    - CACHE_FOLDER=$HOME/docker-images
    - CACHE_FILE=${CACHE_FOLDER}/janna-latest.tar

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - sudo ls -la ${CACHE_FILE}
  - sudo ls -la /var/lib/docker/tmp/
  - mkdir -p /var/lib/docker/tmp/
  - sudo ls -la /var/lib/docker/tmp/
  - sudo ls -la /var/lib/docker/
  - if [[ -f ${CACHE_FILE} ]]; then docker load < ${CACHE_FILE} || true; fi

script:
  - ./build/ci/travis.sh


cache:
  directories:
    - ${CACHE_FOLDER}
