language: minimal

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
    - CACHE_FOLDER=$HOME/docker-images
    - CACHE_FILE=${CACHE_FOLDER}/${NAME}-${TRAVIS_COMMIT}.tgz

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - if [[ -f ${CACHE_FILE} ]]; then docker load -i ${CACHE_FILE}; fi

script:
  - ./build/ci/travis.sh

cache:
  directories:
    - ${CACHE_FOLDER}
