language: minimal

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
    - CACHE_FOLDER=$HOME/docker-images
    - CACHE_FILE=${CACHE_FOLDER}/${NAME}-${TRAVIS_COMMIT}.tgz
jobs:
  include:
    - stage: load cache
      script:
        - if [[ -f ${CACHE_FILE} ]]; then docker load -i ${CACHE_FILE}; fi

    - stage: build
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - ./build/ci/travis.sh

cache:
  directories:
    - ${CACHE_FOLDER}
