// Code generated by mockery v1.0.0. DO NOT EDIT.

package usecase_test

import mock "github.com/stretchr/testify/mock"
import usecase "github.com/vterdunov/janna/internal/virtualmachine/usecase"

// VMRepository is an autogenerated mock type for the VMRepository type
type VMRepository struct {
	mock.Mock
}

// VMDeploy provides a mock function with given fields: params
func (_m *VMRepository) VMDeploy(params usecase.VMDeployRequest) (usecase.VMDeployResponse, error) {
	ret := _m.Called(params)

	var r0 usecase.VMDeployResponse
	if rf, ok := ret.Get(0).(func(usecase.VMDeployRequest) usecase.VMDeployResponse); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(usecase.VMDeployResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(usecase.VMDeployRequest) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VMInfo provides a mock function with given fields: uuid
func (_m *VMRepository) VMInfo(uuid string) (usecase.VMInfoResponse, error) {
	ret := _m.Called(uuid)

	var r0 usecase.VMInfoResponse
	if rf, ok := ret.Get(0).(func(string) usecase.VMInfoResponse); ok {
		r0 = rf(uuid)
	} else {
		r0 = ret.Get(0).(usecase.VMInfoResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
