---
version: '2'

services:
  redis:
    image: redis:5.0.5-alpine
    restart: unless-stopped
    container_name: janna-redis
    env_file: ../.env
    # command: redis-server --requirepass "${REDIS_PASSWORD}"
    logging:
      driver: none

  # redis-ui:
  #   image: marian/rebrow
  #   container_name: redis-ui
  #   restart: unless-stopped
  #   env_file: ../.env
  #   ports:
  #     - "8090:5001"
  #   logging:
  #     driver: none


  api:
    build:
      context: ../
      dockerfile: build/Dockerfile.api
    container_name: api
    env_file: ../.env
    ports:
      - '8081:8081'
    depends_on:
      - 'redis'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  worker:
    build:
      context: ../
      dockerfile: build/Dockerfile.worker
    env_file: ../.env
    restart: unless-stopped
    # ports:
    #   - '2345:2345'
    depends_on:
      - 'redis'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
