// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import virtualmachine "github.com/vterdunov/janna/internal/virtualmachine"

// StatusStorager is an autogenerated mock type for the StatusStorager type
type StatusStorager struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: id
func (_m *StatusStorager) FindByID(id string) virtualmachine.TaskStatuser {
	ret := _m.Called(id)

	var r0 virtualmachine.TaskStatuser
	if rf, ok := ret.Get(0).(func(string) virtualmachine.TaskStatuser); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(virtualmachine.TaskStatuser)
		}
	}

	return r0
}

// NewTask provides a mock function with given fields:
func (_m *StatusStorager) NewTask() virtualmachine.TaskStatuser {
	ret := _m.Called()

	var r0 virtualmachine.TaskStatuser
	if rf, ok := ret.Get(0).(func() virtualmachine.TaskStatuser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(virtualmachine.TaskStatuser)
		}
	}

	return r0
}
