// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import appinfo "github.com/vterdunov/janna/internal/appinfo"
import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetAppInfo provides a mock function with given fields:
func (_m *Repository) GetAppInfo() appinfo.Response {
	ret := _m.Called()

	var r0 appinfo.Response
	if rf, ok := ret.Get(0).(func() appinfo.Response); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(appinfo.Response)
	}

	return r0
}
