// Code generated by mockery v1.0.0. DO NOT EDIT.

package usecase_test

import mock "github.com/stretchr/testify/mock"
import usecase "github.com/vterdunov/janna/internal/usecase"

// AppInfoRepository is an autogenerated mock type for the AppInfoRepository type
type AppInfoRepository struct {
	mock.Mock
}

// AppInfo provides a mock function with given fields:
func (_m *AppInfoRepository) AppInfo() (*usecase.AppInfoResponse, error) {
	ret := _m.Called()

	var r0 *usecase.AppInfoResponse
	if rf, ok := ret.Get(0).(func() *usecase.AppInfoResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.AppInfoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
