// Code generated by mockery v1.0.0. DO NOT EDIT.

package usecase

import mock "github.com/stretchr/testify/mock"

// MockVMWareRepository is an autogenerated mock type for the VMWareRepository type
type MockVMWareRepository struct {
	mock.Mock
}

// VMDeploy provides a mock function with given fields: params
func (_m *MockVMWareRepository) VMDeploy(params VMDeployRequest) (VMDeployResponse, error) {
	ret := _m.Called(params)

	var r0 VMDeployResponse
	if rf, ok := ret.Get(0).(func(VMDeployRequest) VMDeployResponse); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(VMDeployResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(VMDeployRequest) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VMInfo provides a mock function with given fields: uuid
func (_m *MockVMWareRepository) VMInfo(uuid string) (VMInfoResponse, error) {
	ret := _m.Called(uuid)

	var r0 VMInfoResponse
	if rf, ok := ret.Get(0).(func(string) VMInfoResponse); ok {
		r0 = rf(uuid)
	} else {
		r0 = ret.Get(0).(VMInfoResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
